### ISSUE TITLE
New Tab Position doesn't seem to work

### ISSUE THREAD

**Issue by nagaflokhu** [canisbos/TabOptions#3]
Hi,

I have tried setting the New Tab Position to all the possibilities, but none of them work. At first I thought the extension was not working, but New Background Tab Position does work. I am trying to get new tabs to open at the start of the tab bar (leftmost position). I have Safari Version 10.0.3 on macOS Sierra Version 10.12.3. I will be happy to provide you with more information if needed.

Cheers!

**Comment by nagaflokhu** [comment]
An update on this. It seems that New Tab Position is indeed working. I thought it wasn't because I have another extension installed called TabStack, which brings tabs which are focused to the leftmost position, so opening a new tab is a behaving exactly the same as before I got Tab Options.

I think it would be desirable for the "at the start of tab bar" option to open the tab on the left instead of opening it on the right and then bringing it all the way to the left (in other words, the same thing that happens with background tabs when the New Background Tab Position is set to "at the start of tab bar"). My main reason for wanting this is that, when a tab is opened all the way to the right, the tabs at the left become tiny (for lack of a better term), and I have to scroll left in my tabs to be able to read their names. I don't know if this behaviour is possible, but, if it is, it would be very nice to have.

**Comment by canisbos** [comment]
It can't be helped. When you use Safari's built-in UI methods to open a new tab, an extension cannot influence the position of it on the tab bar. It can only move the tab after it has been created.       
  
  
  

  
However, if you use Tab Options's hot key to create a new tab, it will be created in the desired position immediately.   
  
  

  
  
>

**Comment by nagaflokhu** [comment]
Thank you for the quick reply! Do you know if it's possible to make the default new tab shortcut (⌘T) a hot key for Tab Options?

**Comment by canisbos** [comment]
You can, but first you have to change Safari's default keyboard shortcut for New Tab to something else. You can do so in System Preferences > Keyboard > Shortcuts > App Shortcuts.

There is a caveat. Tab Options's hotkeys only work when the keyboard focus is on a web page. Here are some situations in which the extension's hotkeys do not work:

The address bar has the keyboard focus.
The toolbar has the keyboard focus.
The current tab does not contain a web page (it might contain, for example, the Favorites page).

This limitation is due to Safari's extension API. Perhaps the new API, where Safari extensions are like other macOS app extensions, removes this limitation, but I will probably never use the new API due to low motivation.

Chul

**Comment by nagaflokhu** [comment]
Very nice, thanks a lot!
